#!/usr/bin/env bash

echo prerm: Starting...

if [ -f /etc/init/flume.conf ]; then
	status flume | grep -q "^flume start" > /dev/null
	if [ $? == 0 ]; then
		service flume stop
	fi
fi

echo prerm: Done.